CHROMEDRIVER_PATH : "C:\\ChromeDriver\\chromedriver.exe"
FILES_DIRECTORY_NAME : "files"
TEXT_FILE_NAME : "contents.txt"
EMBEDDING_MODEL_NAME : "all-MiniLM-L6-v2"
GEMINI_MODEL_NAME : "gemini-1.5-flash"
GEMINI_API_KEY : "your_gemini_api_key"
LOCAL_VECTOR_STORE_NAME : "faiss_index"